name: "Check file existence"

on: [push, pull_request]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: ".gitignore, LICENSE, README.md" 

    - name: File exists
      if: steps.check_files.outputs.file_exists == 'true'

      run: echo All files exists!